steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - pull

  - name: gcr.io/cloud-builders/docker
    args:
      - build

  - name: gcr.io/my-project/test

  - name: gcr.io/cloud-builders/gsutil
    id: fetch
    waitFor:
      - '-'

  - name: gcr.io/my-project/package
    id: package
    waitFor:
      - fetch
      - test

  - name: gcr.io/ma-project/deploy
