steps:

- name: 'gcr.io/cloud-builders/go'
  args: ['generate']
  id: go-generate

- name: 'gcr.io/cloud-builders/go'
  args: ['test', './...']
  id: go-test

- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'mytarget']
  id: go-install

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', './somefiles', 'gs://my-resource-bucket/somefiles']
  id: fetch-resources
  waitFor: ['-']  # The '-' indicates that this step begins immediately.

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mytarget', '.']
  id: docker-build
  waitFor: ['go-install', 'fetch-resources']

images: ['gcr.io/$PROJECT_ID/mytarget']
