builds:
  - main: ./cmd/cloudbuildgraph/
    env:
      - CGO_ENABLED=0
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - binaries:
      - cloudbuildgraph
    image_templates:
      - "patrickhoefler/cloudbuildgraph:latest"
      - "patrickhoefler/cloudbuildgraph:{{ .Major }}"
      - "patrickhoefler/cloudbuildgraph:{{ .Major }}.{{ .Minor }}"
      - "patrickhoefler/cloudbuildgraph:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
